issues/urls.py
from django.urls import path
from . import views

# имя приложения
app_name = 'issues'
urlpatterns = [
    path('show/', views.index, name='index'),
    path('details/<int:task_id>', views.show_details, name='details'),
]

mainApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('kek/', views.kek, name='kek'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('example/', include('webexample.urls')),
    path('', include('mainApp.urls')),
    path('issue/', include('issues.urls', namespace='issues')),
]

webexample/urls.py
#from django.urls import path
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('test/', views.test, name='test'),
]

issues/models.py
from django.db import models


# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    description = models.TextField(verbose_name='Текст Заявки')
    priority = models.ForeignKey('issues.Priority', on_delete=models.CASCADE, default='---', verbose_name='Приоритет')
    date_start = models.DateTimeField(verbose_name='Дата создания')
    date_end = models.DateTimeField(verbose_name='Дата закрытия', null=True)
    location = models.ForeignKey('issues.Place', on_delete=models.CASCADE, default='---', verbose_name='Местонахождение')
    status = models.ForeignKey('issues.Status', on_delete=models.CASCADE, default='---', verbose_name='Статус')
    assigned = models.CharField(max_length=50, default='---', verbose_name='Исполнитель')
    created = models.CharField(max_length=50, default='---', verbose_name='Создатель заявки')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'


class Priority(models.Model):
    priority_name = models.CharField(max_length=50, verbose_name='Приоритет')

    def __str__(self):
        return self.priority_name

    class Meta:
        verbose_name = 'Приоритет'
        verbose_name_plural = 'Приоритеты'
        ordering = ['id']


class Place(models.Model):
    name_place = models.CharField(max_length=50, verbose_name='Название комнаты')

    def __str__(self):
        return self.name_place

    class Meta:
        verbose_name = 'Комната'
        verbose_name_plural = 'Комнаты'


class Status(models.Model):
    status_name = models.CharField(max_length=50, verbose_name='Статус')

    def __str__(self):
        return self.status_name

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'

mainApp/models.py
from django.db import models

# Create your models here.

task/models.py
from django.db import models

# Create your models here.


class Item(models.Model):
    # task = models.ForeignKey(Task, on_delete = models.CASCADE)
    name = models.CharField(max_length=30, verbose_name='Название')
    number = models.IntegerField(default=0, verbose_name='Колличество')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Оборудование'
        verbose_name_plural = 'Оборудование'


class Task(models.Model):
    title = models.CharField(max_length=30, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    items = models.ForeignKey(Item, on_delete=models.CASCADE, default='---', verbose_name='Оборудование')

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return self.title

webexample/models.py
from django.db import models

# Create your models here.

issues/views.py
from django.shortcuts import render, get_object_or_404
from .models import Task


# Create your views here.

def index(request):
    tasks = Task.objects.all()
    context = {'tasks': tasks}
    return render(request, 'issues/index.html', context)


def show_details(request, task_id):
    task = get_object_or_404(Task, id=task_id)
    context = {'task': task}
    return render(request, 'issues/show_details.html', context)

mainApp/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'mainApp/start_page.html')


# Create your views here.
def kek(request):
    return render(request, 'mainApp/kek.html', {'keki': ['kek1', 'kek2',
                                                         'kek3', 'kek4', 'kek5']})

task/views.py
from django.shortcuts import render

# Create your views here.

webexample/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    return HttpResponse("<h3>Hello World</h3>")

def test(request):
    return HttpResponse("<h3>test</h3>")

issues/templates/issues/index.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
<div class="container" style="background-color: rgba(242, 242, 242, 0.77);">
<div class="col-md-12">
  <h1>Это кек страница</h1>

      {% for task in tasks %}
      {{task.id}}<br>
    <a href="{% url 'issues:details' task.id %}">{{task.title}}</a><br>
        {{task.description}}<br>
        {{task.priority}}<br>
        {{task.date_start}}<br>
        {{task.status}}<br>
        {{task.assigned}}<br>
        <hr>
      {% endfor %}

</div>
</div>
{% endblock %}

issues/templates/issues/show_details.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
<div class="container" style="background-color: rgba(242, 242, 242, 0.77);">
<div class="col-md-12">
  <h1>Это кек страница</h1>


      {{task.title}}<br>
        {{task.description}}<br>
        {{task.priority}}<br>
        {{task.date_start}}<br>
        {{task.status}}<br>
        {{task.assigned}}<br>


</div>
</div>
{% endblock %}

mainApp/templates/mainApp/homePage.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
<div class="container" style="background-color: rgba(242, 242, 242, 0.77);">
<div class="col-md-12">
  <h1>"Это главная страница!"<h1>
</div>
</div>
{% endblock %}

mainApp/templates/mainApp/kek.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
<div class="container" style="background-color: rgba(242, 242, 242, 0.77);">
<div class="col-md-12">
  <h1>Это кек страница<h1>
    <ul>
      {% for val in keki %}
      <li>{{val}}</li>
      {% endfor %}
    </ul>
</div>
</div>
{% endblock %}

mainApp/templates/mainApp/start_page.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
<div class="container" style="background-color: rgba(242, 242, 242, 0.77);">
<div class="col-md-12">
  <h1>"Это стартовая страница появляется при открытии приложения(приветствие логотип)"<h1>
</div>
</div>
{% endblock %}

mainApp/templates/mainApp/wrapper.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>NamePage</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  {% load static %}
  <body style="background-image: url('{% static 'background/1.jpg' %}');">

    <!--navbar-->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="http://127.0.0.1:8000/admin/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>


    {% block content %}
    {% endblock %}
  </body>
</html>

templates/wrapper.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>NamePage</title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  {% load static %}
  <body style="background-image: url('{% static 'background/1.jpg' %}');">

    <!--navbar-->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="http://127.0.0.1:8000/admin/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>


    {% block content %}
    {% endblock %}
  </body>
</html>